name: Play

on:
  workflow_dispatch:
    inputs:
      anything:
        type: string
        required: false

jobs:
  gogogo:
    runs-on: ubuntu-latest
    environment: development
    env:
      ENV: development1
    steps:
      - name: step-one
        shell: bash
        run: |
          echo "${{inputs.anything}}"

      - name: step-two
        shell: bash
        run: |
          echo "${{env.ENV}}"
          echo "${{vars}}"
          echo "${{github}}"
