
name: Play

on:
  workflow_dispatch:
    inputs:
      anything:
        type: string
        required: false

jobs:
  gogogo:
    runs-on: ubuntu-latest
    steps:
      - name: step-one
        shell: bash
        run: |
          echo "${{inputs.anything}}"

      - name: step-two
        shell: bash
        run: |
          echo "aaa"
    
