name: Test play

on:
  push:
    branches:
      - development
      - main

jobs:
  Go:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    env:
      ENV: development1
    steps:
      # - name: checkout
      #   uses: actions/checkout@v6
      #   with:
      #     fetch-depth: 50
      - name: step-one
        shell: bash
        run: |
          ls -al
      # - uses: googleapis/release-please-action@v4
      #   id: release
      #   # if: ${{ vars.ENV == 'production' }} # only master branch bumps
      #   with:
      #     token: ${{ secrets.RELEASE_PLEASE_ACTION_TOKEN }}
      #     target-branch: ${{ github.ref_name }}
      # - name: step-two
      #   shell: bash
      #   run: |
      #     echo "${{env.ENV}}"
      #     echo "${{toJSON(vars)}}"
      # - name: step-three
      #   shell: bash
      #   run: |
      #     echo "${{steps.release.outputs.release_created}}"
      #     echo "${{steps.release.outputs.prs_created}}"
